# Generated by Django 3.2.8 on 2021-10-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eegtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimuli',
            name='order_id',
        ),
        migrations.AddField(
            model_name='stimuli',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order index'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stimulus', to='eegtest.test', verbose_name='Test'),
        ),
    ]
